//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_01_Project
    {
        public int Id { get; set; }
        public string pname { get; set; }
        public string project_id { get; set; }
        public Nullable<int> pici { get; set; }
        public Nullable<System.DateTime> pdate { get; set; }
        public Nullable<System.DateTime> pend { get; set; }
        public string PDM { get; set; }
        public string pType { get; set; }
        public string DesignM { get; set; }
        public string pWork { get; set; }
    }
}
