//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_02_User
    {
        public int Id { get; set; }
        public string uname { get; set; }
        public string upaswd { get; set; }
        public string ugp { get; set; }
        public string ujob { get; set; }
        public string uphone { get; set; }
    }
}
